#!/usr/bin/env python3
"""Regenerate EllesmereUIForeverEssentials/EllesmereUIForeverEssentials_FlightTimerData.lua.

Pulls the TaxiPath and TaxiPathNode tables for a WoW Forever build from
wago.tools and writes the flown length of every route, in yards, keyed by
fromNodeID * 10000 + toNodeID. The runtime turns length into time.

Usage:  python .tools/forever-taxi-lengths.py 1.60.1.69913
"""
import csv
import io
import math
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

OUT = (Path(__file__).resolve().parent.parent / "EllesmereUIForeverEssentials"
       / "EllesmereUIForeverEssentials_FlightTimerData.lua")


def fetch(table, build):
    url = f"https://wago.tools/db2/{table}/csv?build={build}"
    req = urllib.request.Request(url, headers={"User-Agent": "EllesmereUI-tools"})
    with urllib.request.urlopen(req) as resp:
        return list(csv.DictReader(io.StringIO(resp.read().decode("utf-8"))))


def spline_length(pts, steps=16):
    """Length of the Catmull-Rom curve the flight follows through the waypoints."""
    total = 0.0
    for i in range(len(pts) - 1):
        p0 = pts[i - 1] if i > 0 else pts[i]
        p1, p2 = pts[i], pts[i + 1]
        p3 = pts[i + 2] if i + 2 < len(pts) else p2
        prev = p1
        for s in range(1, steps + 1):
            t = s / steps
            t2, t3 = t * t, t * t * t
            cur = tuple(
                0.5 * (2 * b + (c - a) * t + (2 * a - 5 * b + 4 * c - d) * t2 + (3 * b - a - 3 * c + d) * t3)
                for a, b, c, d in zip(p0, p1, p2, p3)
            )
            total += math.dist(prev, cur)
            prev = cur
    return total


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    build = sys.argv[1]

    points = defaultdict(list)
    for r in fetch("TaxiPathNode", build):
        points[r["PathID"]].append((
            int(r["NodeIndex"]), int(r["ContinentID"]), int(r["Delay"]),
            float(r["Loc_0"]), float(r["Loc_1"]), float(r["Loc_2"]),
        ))

    lengths = {}
    for p in fetch("TaxiPath", build):
        pts = sorted(points.get(p["ID"], []))
        if len(pts) < 2:
            continue
        # Boat/zeppelin paths stop at docks (waypoint delays) or cross continents;
        # no flight-master route does either.
        if any(pt[2] for pt in pts) or len({pt[1] for pt in pts}) > 1:
            continue
        from_node, to_node = int(p["FromTaxiNode"]), int(p["ToTaxiNode"])
        if not from_node or not to_node:
            continue
        if from_node >= 10000 or to_node >= 10000:
            sys.exit(f"node id out of key range: {from_node} -> {to_node}")
        lengths[from_node * 10000 + to_node] = round(spline_length([pt[3:] for pt in pts]))

    lines = [
        'if EUI_CLIENT_BLOCKED then return end -- pre-12.1 client failsafe (EllesmereUI_ClientGate.lua)',
        'if not (EllesmereUI and EllesmereUI.IS_FOREVER) then return end',
        '-- Generated by .tools/forever-taxi-lengths.py from WoW Forever build ' + build + '.',
        '-- Flown length of each flight route in yards, keyed fromNodeID * 10000 + toNodeID.',
        'EllesmereUI._FlightTimerRoutes = {',
    ]
    for key in sorted(lengths):
        lines.append(f"    [{key}] = {lengths[key]},")
    lines.append("}")
    OUT.write_text("\r\n".join(lines) + "\r\n", encoding="ascii", newline="")
    print(f"{len(lengths)} routes -> {OUT}")


if __name__ == "__main__":
    main()
